added v1 notification, sortableTable
js-tasks-ru/js-20200622_satbekov16 pull request #5
Opened 2020-07-09 03:52 UTC by k-satbekov

2020-07-09 03:58 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering 
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-07-09 09:33 UTC, dosandk requested changes
В личку отписал проблемы которые нужно решить в PR

2020-07-11 02:24 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
- should be rendered correctly
- should have ability to set slider boundaries
- should have ability to set selected range
- should have ability to move left slider to start boundary
- should have ability to move right slider to end boundary
- should have ability to select all range
- should have ability to select single value (when min and max range equal)
- should have ability to set range value, for example: usd, eur, etc.
- should produce event "range-select"
- should have a new ranges in produced event
- should have ability to be destroyed
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering 
+ should have ability to be destroyed
```

2020-07-11 22:43 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-11 23:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
+ should be rendered correctly
+ should have ability to set slider boundaries
+ should have ability to set selected range
+ should have ability to move left slider to start boundary
+ should have ability to move right slider to end boundary
+ should have ability to select all range
+ should have ability to set range value, for example: usd, eur, etc.
+ should have ability to be destroyed
- should have ability to select single value (when min and max range equal)
- should produce event "range-select"
- should have a new ranges in produced event
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering 
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
- should be hidden when moving out from the element with data-tooltip attribute
- should have ability to be destroyed
```

2020-07-12 00:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
+ should be rendered correctly
+ should have ability to set slider boundaries
+ should have ability to set selected range
+ should have ability to move left slider to start boundary
+ should have ability to move right slider to end boundary
+ should have ability to select all range
+ should have ability to set range value, for example: usd, eur, etc.
+ should have ability to be destroyed
- should have ability to select single value (when min and max range equal)
- should produce event "range-select"
- should have a new ranges in produced event
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering 
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
- should be hidden when moving out from the element with data-tooltip attribute
- should have ability to be destroyed
```

2020-07-12 13:28 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.durationInSeconds = (duration / 1000) + 's';
предпочитайте строковую интерполяцию вместо конкатенации строк
```
this.durationInSeconds = `${duration / 1000}s`;
```

2020-07-12 13:28 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
>  export default class NotificationMessage {
good 👍

2020-07-12 13:31 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        if(item.images) {
этот метод должен быть динамическим, зависеть от данных конфига, вот пример
```
  getTableRow(item) {
    const cells = this.headersConfig.map(({id, template}) => {
      return {
        id,
        template
      };
    });

    return cells.map(({id, template}) => {
      return template
        ? template(item[id])
        : `<div class="sortable-table__cell">${item[id]}</div>`;
    }).join('');
  }
```

2020-07-12 13:33 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    if(orderValue === "asc") {
в этом методе дублируется код, даже несмотря на то что Вы вызываете разные методы: `sortAscNum`, `sortDescNum`, `sortAsc` и `sortDesc` - подумайте как можно избежать повторяющегося кода

2020-07-12 13:33 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    return arr.slice(0).sort((a, b) =>
копирование массивов:
1е, если используете `slice` то аргумент 0 - не нужен
2е - предпочитайте `[...arr]`

2020-07-12 13:34 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  poverRef;
не экономьте на названиях переменных или полей классов, я с трудом догадался что значит `poverRef` и `pmoveRef`

2020-07-12 13:36 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.removeEventListener('pointermove', this.pmoveRef);
не вижу чтобы что-то было присвоено в `this.pmoveRef`

2020-07-12 13:36 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.addEventListener('pointerover', this.poverRef = this.pointerOverEvent.bind(this));
не стоит делать присвоение как часть передачи аргумента функции, сделайте это отдельно

2020-07-12 13:37 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    let target = event.target;
почему здесь `let`???

2020-07-12 13:37 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    let tt = this.element;
что такое `tt`???

2020-07-12 13:38 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  removePointerEvent() {
почему не вызывается данный метод в `destroy`?

2020-07-12 13:39 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +    // const sliderElement = document.createElement('div');
почему закомментирован данный метод?

2020-07-12 13:40 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +    thumbLeftElement.onmousedown = function(event) {
мы же уже договорились что обработчики событий навешиваем через `addEventListener`, здесь какая-то особая задумка?

2020-07-12 13:40 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +        console.log(rInner.getBoundingClientRect().left);
консоли убираем из кода

2020-07-12 13:41 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +    const sliderElement = document.createElement('div');
в данном методе "сборная солянка" и элементы создаются и обработчики навешиваются - нужно разбить на отдельные методы

2020-07-12 13:42 UTC, dosandk requested changes
посмотрите пожалуйста комменты, дайте ответы на вопросы, внесите изменения

2020-07-13 06:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
+ should be rendered correctly
+ should have ability to set slider boundaries
+ should have ability to set selected range
+ should have ability to move left slider to start boundary
+ should have ability to move right slider to end boundary
+ should have ability to select all range
+ should have ability to set range value, for example: usd, eur, etc.
+ should have ability to be destroyed
- should have ability to select single value (when min and max range equal)
- should produce event "range-select"
- should have a new ranges in produced event
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering 
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
- should be hidden when moving out from the element with data-tooltip attribute
- should have ability to be destroyed
```

2020-07-13 08:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
+ should be rendered correctly
+ should have ability to set slider boundaries
+ should have ability to set selected range
+ should have ability to move left slider to start boundary
+ should have ability to move right slider to end boundary
+ should have ability to select all range
+ should have ability to set range value, for example: usd, eur, etc.
+ should have ability to be destroyed
- should have ability to select single value (when min and max range equal)
- should produce event "range-select"
- should have a new ranges in produced event
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering 
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
- should be hidden when moving out from the element with data-tooltip attribute
- should have ability to be destroyed
```

2020-07-18 14:00 UTC, closed without merging