added first version of columnChart dynamic data load, needs to be fixed
js-tasks-ru/js-20200622_satbekov16 pull request #7
Opened 2020-07-20 12:27 UTC by k-satbekov

2020-07-20 12:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
+ should be rendered correctly
+ should have ability to set slider boundaries
+ should have ability to set selected range
+ should have ability to move left slider to start boundary
+ should have ability to move right slider to end boundary
+ should have ability to select single value (when min and max range equal)
+ should have ability to set range value, for example: usd, eur, etc.
+ should produce event "range-select"
+ should have a new ranges in produced event
+ should have ability to be destroyed
- should have ability to select all range
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering 
+ should have ability to be destroyed
```
```diff
ColumnChart компонент с динамической загрузкой данных
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have property 'chartHeight'
+ should render data correctly
- should have ability to be update by new values
- should have loading indication if data wasn't passed 
- should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

2020-07-22 08:15 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  constructor({data = [], label = '', link = '', value = 0} = {}) {
good 👍

2020-07-22 08:15 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  element;
good 👍

2020-07-22 08:16 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.html
> +    console.log(firstRow);
не оставляйте консоли
1. это плохая практика и засоряет код
2. тесты из-за консолей могут не пройти

2020-07-22 08:17 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  sort(fieldValue, orderValue) {
этот метод `sort` было бы неплохо зарефакторить, слишком много вложенности и ветвления логики с `if...else`

2020-07-22 08:18 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  static sortAsc(arr, fieldValue) {
почему эти методы статические?

2020-07-22 08:19 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        if(this.isAsc) {
лучше использовать тернарник:
```
const order = this.isAsc ? 'asc' : 'desc';
```

2020-07-22 08:20 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      arrayItem.addEventListener('pointerdown', () => {
используйте event-delegation вместо навешивания обработчиков через цикл

2020-07-22 08:21 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    } else {
`else` не нужен, так как `return` в блоке `if`

2020-07-22 08:22 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +  onMouseUpRightThumb = () => {
стрелочные функции как свойства класса объявляются до `constructor`

2020-07-22 08:23 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +      response.json().then(data => {
данный метод `async` - поэтому было бы неплохо использовать `await` вместо `.then`

2020-07-22 08:24 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    const requestURL = `https://course-js.javascript.ru/${this.url}?from=${reqDateFrom}&to=${reqDateTo}`;
да, можно так собрать url, но не забывайте про `new URL`

2020-07-22 08:25 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    const response = await fetch(requestURL);
используйте `fetchJson`

2020-07-22 08:25 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    if (month.length < 2)
всегда добавляйте скобки к `if`

2020-07-22 08:26 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +  // update({bodyData: newData}) {
не оставляйте закоментированный код

2020-07-22 08:37 UTC, dosandk requested changes
посмотрите пожалуйста комменты
на вопросы нужно дать ответы
где есть коменты с просьбой исправить - нужно исправить

2020-07-22 11:20 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-23 04:34 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DoubleSlider компонент
+ should be rendered correctly
+ should have ability to set slider boundaries
+ should have ability to set selected range
+ should have ability to move left slider to start boundary
+ should have ability to move right slider to end boundary
+ should have ability to select single value (when min and max range equal)
+ should have ability to set range value, for example: usd, eur, etc.
+ should produce event "range-select"
+ should have a new ranges in produced event
+ should have ability to be destroyed
- should have ability to select all range
```
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
ProductForm v1 компонент с отправкой данных на сервер, без "Drag'n'Drop"
+ should be rendered correctly
+ should render categories data correctly
+ should render product data correctly
+ should dispatch "product-updated" event after product creating
+ should have ability to be removed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering 
+ should have ability to be destroyed
```
```diff
ColumnChart компонент с динамической загрузкой данных
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have property 'chartHeight'
+ should render data correctly
- should have ability to be update by new values
- should have loading indication if data wasn't passed 
- should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

2020-07-23 04:50 UTC, k-satbekov commented on 06-events-practice/2-tooltip/index.js
> +    } else {
Ок исправил

2020-07-23 04:54 UTC, k-satbekov commented on 05-dom-document-loading/2-sortable-table-v1/index.html
> +    console.log(firstRow);
ок удалил

2020-07-23 04:58 UTC, k-satbekov commented on 06-events-practice/3-double-slider/index.js
> +  onMouseUpRightThumb = () => {
ок исправил

2020-07-23 05:24 UTC, k-satbekov commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    const response = await fetch(requestURL);
Да к тому времени я не понял что делает fetchJson, пришлось импровизировать)

2020-07-23 05:25 UTC, k-satbekov commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +  // update({bodyData: newData}) {
убрал, извиняюсь, вы постоянно напоминаете)

2020-07-23 05:26 UTC, k-satbekov commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    if (month.length < 2)
Убрал formatDate метод, понял что лучше как у вас использовать toISOString

2020-07-23 05:29 UTC, closed without merging