Need review on productForm
js-tasks-ru/js-20200622_satbekov16 pull request #8
Opened 2020-07-23 05:34 UTC by k-satbekov

1) Есть проблемы с imageUploader, не могу загрузить фотографию, кажется запрос не принимается на сервере(timeout или что то еще). Видимо неправильная логика   
2) Не вижу статус network запросов в вкладке 'network', допустим когда добавляю продукт или редактирую, все быстро происходит и я не могу увидеть посланные запросы как у вас в примере в описании задания

2020-07-23 05:41 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-24 12:20 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.html
> +  const someData = [
эти изменения нужно откатить!

2020-07-26 18:08 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    if(orderValue === "asc") {
над этим методом стоит подумать, избыточное ветвление присутствует тут,
а в результате ветвления вызов одних и тех же методов

2020-07-26 18:08 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  static sortAsc(arr, fieldValue) {
почему эти методы статические?

2020-07-26 18:09 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    titles.forEach(arrayItem => {
good 👍

2020-07-26 18:09 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        let order;
тернарник подойдет лучше
```
const order = this.isAsc ? 'asc' : 'desc';
```

2020-07-26 18:10 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
>  export default class SortableTable {
good 👍

2020-07-26 18:10 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      const tooltipHtml = targetElement.dataset.tooltip;
используйте деструкцию:
```
const {tooltip} =  targetElement.dataset;
```

2020-07-26 18:11 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
>  class Tooltip {
good 👍

2020-07-26 18:11 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
>  export default class DoubleSlider {
good 👍

2020-07-26 18:12 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
>  export default class ColumnChart {
good 👍

2020-07-26 18:13 UTC, dosandk commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +    const myCustomEventString = this.productId ? 'product-updated' : 'product-saved';
good 👍

2020-07-26 18:14 UTC, dosandk commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +    await this.loadCategories();
загрузка категорий будет тормозить загрузку данных продукта

Это нужно исправить и пустить запросы параллельно

2020-07-26 18:15 UTC, dosandk commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +    const productData = await fetchJson(productUrl);
используйте деструкцию
```
const [productData] = await fetchJson(productUrl);
```

2020-07-26 18:16 UTC, dosandk commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +  getSubcategory(subcategory) {
От этих методов, вплоть до строки 299 можно избавиться просто используя `subElements`

2020-07-26 18:16 UTC, dosandk requested changes
Посмотрите коменты, исправьте замечания

2020-07-26 18:25 UTC, dosandk commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +    imagesList.innerHTML += this.setImagesRow({url: response.data.link, source: selectedFile.name});
вот так `innerHTML +=` делать категорически нельзя так как это выражение эквивалентно
` innerHTML = innerHTML + ...` - другими словами мы каждый раз перетираем все содержимое элемента
В данном случае нужно использовать `append`

2020-07-26 18:27 UTC, dosandk commented on 08-forms-fetch-api-part-2/1-product-form-v1/index.js
> +  submitForm = async event => {
вот здесь необходимо добавить `event.preventDefault();` 
тогда мы отключаем поведение формы по умолчанию и у нас не будет перезагрузки страницы

2020-07-26 21:29 UTC, k-satbekov commented on 05-dom-document-loading/2-sortable-table-v1/index.html
> +  const someData = [
Откатил

2020-07-26 21:33 UTC, k-satbekov commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  static sortAsc(arr, fieldValue) {
Я думал это будет функция способная отсортировать любой массив с любым fieldValue стрингом, независящая от instance variable-ов класса. Вы хотите чтобы я убрал static?

2020-07-26 21:33 UTC, k-satbekov commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    if(orderValue === "asc") {
Изменил метод. В след PR будет другая логика

2020-07-29 07:05 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-30 06:24 UTC, closed without merging